import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/app/components/header";
import Footer from "@/app/components/footer";
import Contact from "@/app/sections/contact";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-full`}>
      <div className="flex flex-col min-h-screen">
          <div className="flex-none">
              <Header />
          </div>
          <div className="flex-auto">
              {children}
          </div>
          <div className="flex-none">
              <Contact />
              <Footer />
          </div>
      </div>
      </body>
    </html>
  )
}
